# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeAddictTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeAddictTask

  pod 'SDWebImageSwiftUI'
  pod 'Alamofire', '~> 5.2'
pod 'AFNetworking', '~> 4.0'
  

end
